# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: container/container.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='container/container.proto',
  package='container',
  syntax='proto3',
  serialized_options=b'\n\023jointfaas.containerB\016ContainerProtoP\001Z\013.;container\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x63ontainer/container.proto\x12\tcontainer\"2\n\rInvokeRequest\x12\x10\n\x08\x66uncName\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x93\x01\n\x0eInvokeResponse\x12,\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1e.container.InvokeResponse.Code\x12\x0e\n\x06output\x18\x02 \x01(\x0c\"C\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\r\n\tNOT_READY\x10\x01\x12\x11\n\rFUNC_MISMATCH\x10\x02\x12\x11\n\rRUNTIME_ERROR\x10\x03\"\x1d\n\x0eSetEnvsRequest\x12\x0b\n\x03\x65nv\x18\x01 \x03(\t\"a\n\x0fSetEnvsResponse\x12-\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1f.container.SetEnvsResponse.Code\"\x1f\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\x0f\n\x0bINVALID_ENV\x10\x01\"0\n\x0fLoadCodeRequest\x12\x10\n\x08\x66uncName\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"]\n\x10LoadCodeResponse\x12.\n\x04\x63ode\x18\x01 \x01(\x0e\x32 .container.LoadCodeResponse.Code\"\x19\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"\r\n\x0bStopRequest\"J\n\x0cStopResponse\x12*\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1c.container.StopResponse.Code\"\x0e\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x32\x92\x02\n\tContainer\x12?\n\x06Invoke\x12\x18.container.InvokeRequest\x1a\x19.container.InvokeResponse\"\x00\x12\x42\n\x07SetEnvs\x12\x19.container.SetEnvsRequest\x1a\x1a.container.SetEnvsResponse\"\x00\x12\x45\n\x08LoadCode\x12\x1a.container.LoadCodeRequest\x1a\x1b.container.LoadCodeResponse\"\x00\x12\x39\n\x04Stop\x12\x16.container.StopRequest\x1a\x17.container.StopResponse\"\x00\x42:\n\x13jointfaas.containerB\x0e\x43ontainerProtoP\x01Z\x0b.;container\xa2\x02\x03HLWb\x06proto3'
)



_INVOKERESPONSE_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='container.InvokeResponse.Code',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOT_READY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FUNC_MISMATCH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUNTIME_ERROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=173,
  serialized_end=240,
)
_sym_db.RegisterEnumDescriptor(_INVOKERESPONSE_CODE)

_SETENVSRESPONSE_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='container.SetEnvsResponse.Code',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INVALID_ENV', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=339,
  serialized_end=370,
)
_sym_db.RegisterEnumDescriptor(_SETENVSRESPONSE_CODE)

_LOADCODERESPONSE_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='container.LoadCodeResponse.Code',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=490,
  serialized_end=515,
)
_sym_db.RegisterEnumDescriptor(_LOADCODERESPONSE_CODE)

_STOPRESPONSE_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='container.StopResponse.Code',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=173,
  serialized_end=187,
)
_sym_db.RegisterEnumDescriptor(_STOPRESPONSE_CODE)


_INVOKEREQUEST = _descriptor.Descriptor(
  name='InvokeRequest',
  full_name='container.InvokeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='funcName', full_name='container.InvokeRequest.funcName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='container.InvokeRequest.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=90,
)


_INVOKERESPONSE = _descriptor.Descriptor(
  name='InvokeResponse',
  full_name='container.InvokeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='container.InvokeResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='container.InvokeResponse.output', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INVOKERESPONSE_CODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=240,
)


_SETENVSREQUEST = _descriptor.Descriptor(
  name='SetEnvsRequest',
  full_name='container.SetEnvsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='env', full_name='container.SetEnvsRequest.env', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=271,
)


_SETENVSRESPONSE = _descriptor.Descriptor(
  name='SetEnvsResponse',
  full_name='container.SetEnvsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='container.SetEnvsResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETENVSRESPONSE_CODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=370,
)


_LOADCODEREQUEST = _descriptor.Descriptor(
  name='LoadCodeRequest',
  full_name='container.LoadCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='funcName', full_name='container.LoadCodeRequest.funcName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='container.LoadCodeRequest.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=420,
)


_LOADCODERESPONSE = _descriptor.Descriptor(
  name='LoadCodeResponse',
  full_name='container.LoadCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='container.LoadCodeResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOADCODERESPONSE_CODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=515,
)


_STOPREQUEST = _descriptor.Descriptor(
  name='StopRequest',
  full_name='container.StopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=530,
)


_STOPRESPONSE = _descriptor.Descriptor(
  name='StopResponse',
  full_name='container.StopResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='container.StopResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STOPRESPONSE_CODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=606,
)

_INVOKERESPONSE.fields_by_name['code'].enum_type = _INVOKERESPONSE_CODE
_INVOKERESPONSE_CODE.containing_type = _INVOKERESPONSE
_SETENVSRESPONSE.fields_by_name['code'].enum_type = _SETENVSRESPONSE_CODE
_SETENVSRESPONSE_CODE.containing_type = _SETENVSRESPONSE
_LOADCODERESPONSE.fields_by_name['code'].enum_type = _LOADCODERESPONSE_CODE
_LOADCODERESPONSE_CODE.containing_type = _LOADCODERESPONSE
_STOPRESPONSE.fields_by_name['code'].enum_type = _STOPRESPONSE_CODE
_STOPRESPONSE_CODE.containing_type = _STOPRESPONSE
DESCRIPTOR.message_types_by_name['InvokeRequest'] = _INVOKEREQUEST
DESCRIPTOR.message_types_by_name['InvokeResponse'] = _INVOKERESPONSE
DESCRIPTOR.message_types_by_name['SetEnvsRequest'] = _SETENVSREQUEST
DESCRIPTOR.message_types_by_name['SetEnvsResponse'] = _SETENVSRESPONSE
DESCRIPTOR.message_types_by_name['LoadCodeRequest'] = _LOADCODEREQUEST
DESCRIPTOR.message_types_by_name['LoadCodeResponse'] = _LOADCODERESPONSE
DESCRIPTOR.message_types_by_name['StopRequest'] = _STOPREQUEST
DESCRIPTOR.message_types_by_name['StopResponse'] = _STOPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InvokeRequest = _reflection.GeneratedProtocolMessageType('InvokeRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOKEREQUEST,
  '__module__' : 'container.container_pb2'
  # @@protoc_insertion_point(class_scope:container.InvokeRequest)
  })
_sym_db.RegisterMessage(InvokeRequest)

InvokeResponse = _reflection.GeneratedProtocolMessageType('InvokeResponse', (_message.Message,), {
  'DESCRIPTOR' : _INVOKERESPONSE,
  '__module__' : 'container.container_pb2'
  # @@protoc_insertion_point(class_scope:container.InvokeResponse)
  })
_sym_db.RegisterMessage(InvokeResponse)

SetEnvsRequest = _reflection.GeneratedProtocolMessageType('SetEnvsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETENVSREQUEST,
  '__module__' : 'container.container_pb2'
  # @@protoc_insertion_point(class_scope:container.SetEnvsRequest)
  })
_sym_db.RegisterMessage(SetEnvsRequest)

SetEnvsResponse = _reflection.GeneratedProtocolMessageType('SetEnvsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETENVSRESPONSE,
  '__module__' : 'container.container_pb2'
  # @@protoc_insertion_point(class_scope:container.SetEnvsResponse)
  })
_sym_db.RegisterMessage(SetEnvsResponse)

LoadCodeRequest = _reflection.GeneratedProtocolMessageType('LoadCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOADCODEREQUEST,
  '__module__' : 'container.container_pb2'
  # @@protoc_insertion_point(class_scope:container.LoadCodeRequest)
  })
_sym_db.RegisterMessage(LoadCodeRequest)

LoadCodeResponse = _reflection.GeneratedProtocolMessageType('LoadCodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOADCODERESPONSE,
  '__module__' : 'container.container_pb2'
  # @@protoc_insertion_point(class_scope:container.LoadCodeResponse)
  })
_sym_db.RegisterMessage(LoadCodeResponse)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPREQUEST,
  '__module__' : 'container.container_pb2'
  # @@protoc_insertion_point(class_scope:container.StopRequest)
  })
_sym_db.RegisterMessage(StopRequest)

StopResponse = _reflection.GeneratedProtocolMessageType('StopResponse', (_message.Message,), {
  'DESCRIPTOR' : _STOPRESPONSE,
  '__module__' : 'container.container_pb2'
  # @@protoc_insertion_point(class_scope:container.StopResponse)
  })
_sym_db.RegisterMessage(StopResponse)


DESCRIPTOR._options = None

_CONTAINER = _descriptor.ServiceDescriptor(
  name='Container',
  full_name='container.Container',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=609,
  serialized_end=883,
  methods=[
  _descriptor.MethodDescriptor(
    name='Invoke',
    full_name='container.Container.Invoke',
    index=0,
    containing_service=None,
    input_type=_INVOKEREQUEST,
    output_type=_INVOKERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetEnvs',
    full_name='container.Container.SetEnvs',
    index=1,
    containing_service=None,
    input_type=_SETENVSREQUEST,
    output_type=_SETENVSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LoadCode',
    full_name='container.Container.LoadCode',
    index=2,
    containing_service=None,
    input_type=_LOADCODEREQUEST,
    output_type=_LOADCODERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Stop',
    full_name='container.Container.Stop',
    index=3,
    containing_service=None,
    input_type=_STOPREQUEST,
    output_type=_STOPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTAINER)

DESCRIPTOR.services_by_name['Container'] = _CONTAINER

# @@protoc_insertion_point(module_scope)
