# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from discovery import discovery_pb2 as discovery_dot_discovery__pb2


class DiscoveryServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.XDS = channel.stream_stream(
                '/mesh.discovery.DiscoveryServer/XDS',
                request_serializer=discovery_dot_discovery__pb2.XDSRequest.SerializeToString,
                response_deserializer=discovery_dot_discovery__pb2.XDSResponse.FromString,
                )


class DiscoveryServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def XDS(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'XDS': grpc.stream_stream_rpc_method_handler(
                    servicer.XDS,
                    request_deserializer=discovery_dot_discovery__pb2.XDSRequest.FromString,
                    response_serializer=discovery_dot_discovery__pb2.XDSResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mesh.discovery.DiscoveryServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscoveryServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def XDS(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/mesh.discovery.DiscoveryServer/XDS',
            discovery_dot_discovery__pb2.XDSRequest.SerializeToString,
            discovery_dot_discovery__pb2.XDSResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
