# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discovery/discovery.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='discovery/discovery.proto',
  package='mesh.discovery',
  syntax='proto3',
  serialized_options=b'\n\030jointfaas.mesh.discoveryZ5ipads.se.sjtu.edu.cn/mesh-control-plane/pkg/discovery',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x64iscovery/discovery.proto\x12\x0emesh.discovery\x1a\x19google/protobuf/any.proto\"|\n\nXDSRequest\x12*\n\x08instance\x18\x01 \x01(\x0b\x32\x18.mesh.discovery.Instance\x12\x14\n\x0cresourceType\x18\x02 \x01(\t\x12\x15\n\rresourcesName\x18\x03 \x03(\t\x12\x15\n\rresponseNonce\x18\x04 \x01(\t\"c\n\x0bXDSResponse\x12\'\n\tresources\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\x12\x15\n\rresponseNonce\x18\x02 \x01(\t\x12\x14\n\x0cresourceType\x18\x03 \x01(\t\"X\n\x08Instance\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x14\n\x0c\x66unctionName\x18\x02 \x01(\t\x12\x17\n\x0f\x61pplicationName\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t2W\n\x0f\x44iscoveryServer\x12\x44\n\x03XDS\x12\x1a.mesh.discovery.XDSRequest\x1a\x1b.mesh.discovery.XDSResponse\"\x00(\x01\x30\x01\x42Q\n\x18jointfaas.mesh.discoveryZ5ipads.se.sjtu.edu.cn/mesh-control-plane/pkg/discoveryb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_XDSREQUEST = _descriptor.Descriptor(
  name='XDSRequest',
  full_name='mesh.discovery.XDSRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='mesh.discovery.XDSRequest.instance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resourceType', full_name='mesh.discovery.XDSRequest.resourceType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resourcesName', full_name='mesh.discovery.XDSRequest.resourcesName', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseNonce', full_name='mesh.discovery.XDSRequest.responseNonce', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=196,
)


_XDSRESPONSE = _descriptor.Descriptor(
  name='XDSResponse',
  full_name='mesh.discovery.XDSResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resources', full_name='mesh.discovery.XDSResponse.resources', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseNonce', full_name='mesh.discovery.XDSResponse.responseNonce', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resourceType', full_name='mesh.discovery.XDSResponse.resourceType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=297,
)


_INSTANCE = _descriptor.Descriptor(
  name='Instance',
  full_name='mesh.discovery.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider', full_name='mesh.discovery.Instance.provider', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='functionName', full_name='mesh.discovery.Instance.functionName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='applicationName', full_name='mesh.discovery.Instance.applicationName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='mesh.discovery.Instance.url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=387,
)

_XDSREQUEST.fields_by_name['instance'].message_type = _INSTANCE
_XDSRESPONSE.fields_by_name['resources'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['XDSRequest'] = _XDSREQUEST
DESCRIPTOR.message_types_by_name['XDSResponse'] = _XDSRESPONSE
DESCRIPTOR.message_types_by_name['Instance'] = _INSTANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XDSRequest = _reflection.GeneratedProtocolMessageType('XDSRequest', (_message.Message,), {
  'DESCRIPTOR' : _XDSREQUEST,
  '__module__' : 'discovery.discovery_pb2'
  # @@protoc_insertion_point(class_scope:mesh.discovery.XDSRequest)
  })
_sym_db.RegisterMessage(XDSRequest)

XDSResponse = _reflection.GeneratedProtocolMessageType('XDSResponse', (_message.Message,), {
  'DESCRIPTOR' : _XDSRESPONSE,
  '__module__' : 'discovery.discovery_pb2'
  # @@protoc_insertion_point(class_scope:mesh.discovery.XDSResponse)
  })
_sym_db.RegisterMessage(XDSResponse)

Instance = _reflection.GeneratedProtocolMessageType('Instance', (_message.Message,), {
  'DESCRIPTOR' : _INSTANCE,
  '__module__' : 'discovery.discovery_pb2'
  # @@protoc_insertion_point(class_scope:mesh.discovery.Instance)
  })
_sym_db.RegisterMessage(Instance)


DESCRIPTOR._options = None

_DISCOVERYSERVER = _descriptor.ServiceDescriptor(
  name='DiscoveryServer',
  full_name='mesh.discovery.DiscoveryServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=389,
  serialized_end=476,
  methods=[
  _descriptor.MethodDescriptor(
    name='XDS',
    full_name='mesh.discovery.DiscoveryServer.XDS',
    index=0,
    containing_service=None,
    input_type=_XDSREQUEST,
    output_type=_XDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOVERYSERVER)

DESCRIPTOR.services_by_name['DiscoveryServer'] = _DISCOVERYSERVER

# @@protoc_insertion_point(module_scope)
